// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ubyiaetfzlsgqjzxrpld.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVieWlhZXRmemxzZ3FqenhycGxkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNTI4MzUsImV4cCI6MjA2NDYyODgzNX0.PP9Z05y914rhUQZCZJjBAMxeV21bds5QRrbjXV8xGrA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);